version: "3.7"

services:
  blog:
    build: 
      context: .
      target: dev
    image: abkfenris/blog
    # command: yarn next build
    # command: yarn serve
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - /app/node_modules/